# Blackhole Configuration

orchestrator:
  socket_dir: ./sockets
  plugins_dir: ./bin/plugins
  log_level: info
  
plugins:
  # Plugin configurations
  node:
    enabled: true
    source:
      type: local
      path: ./core/pkg/plugins/node
    isolation: process
    resources:
      cpu: 50        # 50% of CPU
      memory: 256    # MB
      network: 100   # Mbps
    config:
      log_level: info
      p2p_port: 4001
      bootstrap_peers: []
      
  # Future plugins can be added here
  # storage:
  #   enabled: false
  #   source:
  #     type: marketplace
  #     id: "official/storage"
  #   ...
  
# Mesh network configuration
mesh:
  discovery:
    enabled: true
    method: mdns  # multicast DNS for local discovery
  
  transport:
    protocol: tcp
    encryption: tls
    
# Framework configuration
framework:
  runtime:
    health_check_interval: 30s
    max_plugin_restarts: 3
    
  economics:
    metering_enabled: false
    billing_endpoint: ""
    
  resources:
    global_limits:
      total_cpu: 800      # 8 CPU cores
      total_memory: 8192  # 8GB
      total_disk: 100000  # 100GB