# Blackhole Configuration

orchestrator:
  socket_dir: ./sockets
  services_dir: ./bin/services
  log_level: info
  
services:
  # Enable available services with actual binaries
  identity:
    enabled: true
    resources:
      cpu: 200        # 200% = 2 CPU cores
      memory: 1024    # MB
      io_weight: 500  # Medium I/O priority
    config:
      log_level: info
      port: 9001
      
  node:
    enabled: true
    resources:
      cpu: 300        # 300% = 3 CPU cores (P2P networking intensive)
      memory: 2048    # MB
      io_weight: 700  # High I/O priority for P2P
    config:
      log_level: info
      port: 9002
      p2p_port: 4001
      
  # Test service for integration testing
  test-service:
    enabled: false
    resources:
      cpu: 100        # 100% = 1 CPU core
      memory: 512     # MB
      io_weight: 500  # Medium I/O priority
    config:
      log_level: info