# Node Service Configuration Example
node_id: "blackhole-node-1"
version: "1.0.0"

# Network configuration
listen_port: 9000
listen_address: "0.0.0.0"
external_ip: ""

# P2P Configuration
p2p:
  # Identity configuration
  private_key_path: ""
  
  # Transport configuration
  enable_tcp: true
  enable_quic: true
  enable_websocket: false
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/9000"
    - "/ip4/0.0.0.0/udp/9000/quic-v1"
  
  # Security configuration
  enable_noise: true
  enable_tls: false
  
  # Discovery configuration
  enable_mdns: true
  mdns_interval: "10s"
  enable_dht: true
  dht_mode: "auto"  # "client", "server", "auto"
  bootstrap_peers:
    - "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"
    - "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
  
  # Connection management
  low_water_mark: 50
  high_water_mark: 100
  grace_period: "30s"
  
  # Resource management
  max_streams: 1000
  max_inbound_streams: 500
  max_outbound_streams: 500
  max_memory: 1073741824  # 1GB

# Peer limits
max_peers: 100
min_peers: 5
connection_timeout: "30s"
ping_interval: "30s"

# Discovery configuration (legacy)
bootstrap_peers:
  - "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
discovery_methods:
  - "dht"
  - "bootstrap"
  - "connected"

# DHT configuration (legacy)
dht:
  enabled: true
  refresh_interval: "10m"
  bucket_size: 20

# Performance configuration
bandwidth_limit: 0  # 0 = unlimited
message_queue_size: 1000

# Security configuration (legacy)
enable_tls: false
tls_cert_path: ""
tls_key_path: ""