name: Update Marketplace Catalog

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      plugin_id:
        description: 'Plugin ID to update'
        required: false
        type: string

jobs:
  update-catalog:
    if: startsWith(github.event.release.tag_name, 'plugin-') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract plugin info from release
        if: github.event_name == 'release'
        id: plugin-info
        run: |
          # Extract plugin ID and version from tag (e.g., plugin-node-v1.0.0)
          TAG="${{ github.event.release.tag_name }}"
          PLUGIN_ID=$(echo $TAG | sed 's/plugin-\(.*\)-v.*/\1/')
          VERSION=$(echo $TAG | sed 's/.*-v//')
          echo "plugin_id=$PLUGIN_ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Update plugin metadata
        run: |
          PLUGIN_ID="${{ steps.plugin-info.outputs.plugin_id || github.event.inputs.plugin_id }}"
          VERSION="${{ steps.plugin-info.outputs.version || 'latest' }}"
          
          # Download plugin manifest from release assets
          if [ "${{ github.event_name }}" == "release" ]; then
            # Get plugin.yaml from release assets
            MANIFEST_URL=$(gh release view ${{ github.event.release.tag_name }} --json assets \
              | jq -r '.assets[] | select(.name == "plugin.yaml") | .url')
            
            if [ -n "$MANIFEST_URL" ]; then
              curl -L -o /tmp/plugin.yaml "$MANIFEST_URL"
              
              # Convert plugin.yaml to marketplace JSON format
              python3 scripts/convert-plugin-manifest.py /tmp/plugin.yaml \
                > ecosystem/marketplace/catalog/official/${PLUGIN_ID}.json
            fi
          fi
      
      - name: Rebuild catalog
        run: |
          cd ecosystem/marketplace
          bash scripts/build-catalog.sh
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ecosystem/marketplace/
          git commit -m "Update marketplace catalog for ${{ steps.plugin-info.outputs.plugin_id || github.event.inputs.plugin_id }}" || exit 0
          git push